services:
  postgres:
    image: 'postgres:15'
    container_name: ziirocrm-postgres15
    restart: always
    environment:
      POSTGRES_DB: ziirocrm
      POSTGRES_USER: ziirocrm
      POSTGRES_PASSWORD: ziirocrm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
